# Generated by Django 5.2.9 on 2026-08-12 22:37

import contracts.storage_paths
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('organizations', '0001_initial'),
        # extracted_textのGinIndex(gin_trgm_ops)がpg_trgm拡張を必要とするため、
        # 拡張を有効化するcore.migrations.0001_enable_pg_trgmへの依存を明示する。
        ('core', '0001_enable_pg_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='契約書タイトル')),
                ('year', models.PositiveIntegerField(verbose_name='年')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='契約日')),
                ('contract_period_start', models.DateField(blank=True, null=True, verbose_name='契約期間(開始)')),
                ('contract_period_end', models.DateField(blank=True, null=True, verbose_name='契約期間(終了)')),
                ('renewal_date', models.DateField(blank=True, null=True, verbose_name='契約更新日')),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='契約金額')),
                ('contract_partner', models.CharField(blank=True, default='', max_length=255, verbose_name='契約先名')),
                ('expiry_date', models.DateField(help_text='保存日 + masters.SystemSetting.contract_retention_years から算出して保存する', verbose_name='保存満了日')),
                ('memo', models.TextField(blank=True, default='', verbose_name='メモ')),
                ('file', models.FileField(upload_to=contracts.storage_paths.contract_upload_path, verbose_name='ファイル')),
                ('extracted_text', models.TextField(blank=True, default='', help_text='ファイルから抽出した本文テキスト。フリーワード全文検索の対象', verbose_name='抽出本文')),
                ('ocr_attempted', models.BooleanField(default=False, help_text='documents.Document.ocr_attemptedと同じ理由で追加（core.management.commands.extract_pending_pdf_text参照）。', verbose_name='OCR実行済み')),
                ('searchable_file', models.FileField(blank=True, help_text='documents.Document.searchable_fileと同じ理由で追加（同モデルのhelp_text参照）。', null=True, upload_to=contracts.storage_paths.contract_searchable_upload_path, verbose_name='検索用PDF（OCRテキスト埋め込み版）')),
                ('save_date', models.DateTimeField(auto_now_add=True, verbose_name='保存日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除済み')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='masters.category', verbose_name='カテゴリー')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='organizations.department', verbose_name='保管先部署')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='masters.group', verbose_name='分類')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_contracts', to=settings.AUTH_USER_MODEL, verbose_name='保管・更新者')),
            ],
            options={
                'verbose_name': '契約書',
                'verbose_name_plural': '契約書',
                'db_table': 't_contract',
            },
        ),
        migrations.CreateModel(
            name='RelatedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=contracts.storage_paths.related_file_upload_path, verbose_name='ファイル')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_files', to='contracts.contract', verbose_name='契約書')),
            ],
            options={
                'verbose_name': '関連書類',
                'verbose_name_plural': '関連書類',
                'db_table': 't_contract_attachment',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=django.contrib.postgres.indexes.GinIndex(fields=['extracted_text'], name='contract_extracted_text_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
