# Generated by Django 5.2.9 on 2026-08-26 06:37

import contracts.storage_paths
import core.upload_validation
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('organizations', '0001_initial'),
        ('core', '0001_enable_pg_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='契約書タイトル')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2200)], verbose_name='年')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='契約日')),
                ('contract_period_start', models.DateField(blank=True, null=True, verbose_name='契約期間(開始)')),
                ('contract_period_end', models.DateField(blank=True, null=True, verbose_name='契約期間(終了)')),
                ('renewal_date', models.DateField(blank=True, null=True, verbose_name='契約更新日')),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='契約金額')),
                ('contract_partner', models.CharField(blank=True, default='', max_length=255, verbose_name='契約先名')),
                ('expiry_date', models.DateField(db_index=True, help_text='保存日 + settings.CONTRACT_RETENTION_YEARS から算出して保存する', verbose_name='保存満了日')),
                ('memo', models.TextField(blank=True, default='', verbose_name='メモ')),
                ('file', models.FileField(upload_to=contracts.storage_paths.contract_upload_path, validators=[core.upload_validation.validate_no_active_content], verbose_name='ファイル')),
                ('extracted_text', models.TextField(blank=True, default='', help_text='ファイルから抽出した本文テキスト。フリーワード全文検索の対象', verbose_name='抽出本文')),
                ('title_normalized', models.TextField(blank=True, default='', editable=False)),
                ('memo_normalized', models.TextField(blank=True, default='', editable=False)),
                ('extracted_text_normalized', models.TextField(blank=True, default='', editable=False)),
                ('ocr_attempted', models.BooleanField(default=False, help_text='documents.Document.ocr_attemptedと同じ理由で追加（core.management.commands.extract_pending_pdf_text参照）。', verbose_name='OCR実行済み')),
                ('searchable_file', models.FileField(blank=True, help_text='documents.Document.searchable_fileと同じ理由で追加（同モデルのhelp_text参照）。ただしContractにはprivacy_flag（個人情報フラグ）が無いため、documents.Documentと異なりファイル単位の除外判定は行わず、settings.OCR_EMBED_TEXT_TO_PDFのみに従って埋め込む（core.management.commands.extract_pending_pdf_text._should_embed参照）。', null=True, upload_to=contracts.storage_paths.contract_searchable_upload_path, verbose_name='検索用PDF（OCRテキスト埋め込み版）')),
                ('save_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='保存日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除済み')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='masters.category', verbose_name='カテゴリー')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='organizations.department', verbose_name='保管先部署')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='masters.group', verbose_name='分類')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_contracts', to=settings.AUTH_USER_MODEL, verbose_name='保管・更新者')),
            ],
            options={
                'verbose_name': '契約書',
                'verbose_name_plural': '契約書',
                'db_table': 't_contract',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['title_normalized'], name='contract_title_norm_trgm', opclasses=['gin_trgm_ops']), django.contrib.postgres.indexes.GinIndex(fields=['memo_normalized'], name='contract_memo_norm_trgm', opclasses=['gin_trgm_ops']), django.contrib.postgres.indexes.GinIndex(fields=['extracted_text_normalized'], name='contract_extr_text_norm_trgm', opclasses=['gin_trgm_ops']), models.Index(condition=models.Q(('is_deleted', True)), fields=['deleted_at'], name='contract_deleted_at_partial')],
                'constraints': [models.CheckConstraint(condition=models.Q(('contract_period_start__lte', models.F('contract_period_end')), ('contract_period_start__isnull', True), ('contract_period_end__isnull', True), _connector='OR'), name='contract_period_start_before_end')],
            },
        ),
        # 関連書類（screen-storage2契約書モード）。簡易設計指示書 Rev1.6（xlsx 保管!B478-484）で
        # 「物理ファイルのアップロード（旧 RelatedFile）」→「既に保管済みの契約書をポップアップ検索して
        # 複数紐付ける」方式に転換。本番リリース前のため旧 RelatedFile（t_contract_attachment）の
        # マイグレーション履歴は残さず、この 0001 に ContractRelation として直接畳み込んだ
        # （2026-09-09、ユーザー依頼。詳細は HTML_REIMPL_CHECKLIST_ARCHIVE.md「R6-1」節）。
        migrations.CreateModel(
            name='ContractRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='contracts.contract', verbose_name='契約書')),
                ('related_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_from', to='contracts.contract', verbose_name='関連書類（契約書）')),
            ],
            options={
                'verbose_name': '関連書類',
                'verbose_name_plural': '関連書類',
                'db_table': 't_contract_relation',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='contractrelation',
            constraint=models.UniqueConstraint(fields=('contract', 'related_contract'), name='uniq_contract_relation'),
        ),
        migrations.AddConstraint(
            model_name='contractrelation',
            constraint=models.CheckConstraint(condition=models.Q(('contract', models.F('related_contract')), _negated=True), name='no_self_contract_relation'),
        ),
    ]
