# Generated by Django 5.2.9 on 2026-08-17 01:17

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('masters', '0002_remove_systemsetting_contract_retention_years_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='extracted_text_normalized',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='memo_normalized',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='title_normalized',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=django.contrib.postgres.indexes.GinIndex(fields=['extracted_text_normalized'], name='contract_extr_text_norm_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
