# Generated by Django 5.2.9 on 2026-08-24 00:12

import contracts.storage_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_backfill_normalized_search_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='searchable_file',
            field=models.FileField(blank=True, help_text='documents.Document.searchable_fileと同じ理由で追加（同モデルのhelp_text参照）。ただしContractにはprivacy_flag（個人情報フラグ）が無いため、documents.Documentと異なりファイル単位の除外判定は行わず、settings.OCR_EMBED_TEXT_TO_PDFのみに従って埋め込む（core.management.commands.extract_pending_pdf_text._should_embed参照）。', null=True, upload_to=contracts.storage_paths.contract_searchable_upload_path, verbose_name='検索用PDF（OCRテキスト埋め込み版）'),
        ),
    ]
