# Generated by Django 5.2.9 on 2026-08-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contract_searchable_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='expiry_date',
            field=models.DateField(help_text='保存日 + settings.CONTRACT_RETENTION_YEARS から算出して保存する', verbose_name='保存満了日'),
        ),
    ]
