# Generated by Django 5.2.9 on 2026-08-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_contract_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='title_normalized',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
