# Generated by Django 5.2.9 on 2026-08-26 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_idle_timeout_minutes', models.PositiveIntegerField(default=60, verbose_name='自動ログアウト時間(分)')),
                ('audit_log_retention_months', models.PositiveIntegerField(default=3, help_text='CSV出力の最大対象期間でもある（xlsx 操作履歴ログ!B48-49）', verbose_name='操作履歴ログ最大保存期間(ヵ月)')),
            ],
            options={
                'verbose_name': 'システム設定',
                'verbose_name_plural': 'システム設定',
                'db_table': 'm_system_setting',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='分類コード')),
                ('name', models.CharField(max_length=100, verbose_name='分類名')),
                ('doc_kbn', models.CharField(choices=[('document', '文書管理'), ('contract', '契約書管理')], max_length=10, verbose_name='書類管理区分')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.department', verbose_name='部署')),
            ],
            options={
                'verbose_name': '分類',
                'verbose_name_plural': '分類マスタ',
                'db_table': 'm_group',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='カテゴリーコード')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリー名')),
                ('doc_kbn', models.CharField(choices=[('document', '文書管理'), ('contract', '契約書管理')], max_length=10, verbose_name='書類管理区分')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.department', verbose_name='部署')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='masters.group', verbose_name='分類')),
            ],
            options={
                'verbose_name': 'カテゴリー',
                'verbose_name_plural': 'カテゴリーマスタ',
                'db_table': 'm_category',
            },
        ),
        migrations.CreateModel(
            name='RetentionPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kbn', models.CharField(choices=[('document', '文書'), ('eapproval', '電子決裁')], max_length=10, verbose_name='区分')),
                ('doc_name', models.CharField(blank=True, choices=[('ringisho', '稟議書'), ('keihi', '経費支出伺')], default='', max_length=20, verbose_name='書類名（電子決裁のみ）')),
                ('period_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='保存期間')),
                ('period_unit', models.CharField(choices=[('month', 'ヵ月'), ('year', '年'), ('permanent', '永年')], max_length=10, verbose_name='保存期間単位')),
                ('display_order', models.PositiveIntegerField(verbose_name='表示順')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除済み')),
            ],
            options={
                'verbose_name': '保存期間設定',
                'verbose_name_plural': '保存期間設定',
                'db_table': 'm_retention_period',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('kbn', 'doc_name', 'display_order'), name='unique_retention_display_order'), models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('kbn', 'doc_name', 'period_value', 'period_unit'), name='unique_retention_period_value'), models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('period_unit', 'permanent')), fields=('kbn', 'doc_name'), name='unique_retention_permanent')],
            },
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='unique_group_code'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='unique_category_code'),
        ),
    ]
