# Generated by Django 5.2.9 on 2026-08-13 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsetting',
            name='contract_retention_years',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='notice_threshold_months',
        ),
    ]
