# Generated by Django 5.2.9 on 2026-08-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_remove_systemsetting_contract_retention_years_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='retentionperiod',
            name='unique_retention_display_order',
        ),
        migrations.AddField(
            model_name='retentionperiod',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='削除済み'),
        ),
        migrations.AddConstraint(
            model_name='retentionperiod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('kbn', 'doc_name', 'display_order'), name='unique_retention_display_order'),
        ),
    ]
