# Generated by Django 5.2.9 on 2026-08-23 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_retentionperiod_is_deleted'),
        ('organizations', '0002_departmentviewscope'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.department', verbose_name='部署'),
        ),
        migrations.AddField(
            model_name='group',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.department', verbose_name='部署'),
        ),
    ]
