# Generated by Django 5.2.9 on 2026-08-26 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=10, verbose_name='本支所コード')),
                ('branch_name', models.CharField(max_length=100, verbose_name='本支所名')),
                ('section_code', models.CharField(max_length=10, verbose_name='部課コード')),
                ('section_name', models.CharField(max_length=100, verbose_name='部課名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '部署',
                'verbose_name_plural': '部署マスタ',
                'db_table': 'm_department',
                'constraints': [models.UniqueConstraint(fields=('branch_code', 'section_code'), name='unique_department_branch_section')],
            },
        ),
        migrations.CreateModel(
            name='MenuItemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_search_document', models.BooleanField(default=False, verbose_name='検索・閲覧・変更-文書')),
                ('show_search_contract', models.BooleanField(default=False, verbose_name='検索・閲覧・変更-契約書')),
                ('show_search_eapproval', models.BooleanField(default=False, verbose_name='検索・閲覧・変更-電子決裁')),
                ('show_storage_document', models.BooleanField(default=False, verbose_name='保管-文書')),
                ('show_storage_contract', models.BooleanField(default=False, verbose_name='保管-契約書')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_setting', to='organizations.department', verbose_name='部署')),
            ],
            options={
                'verbose_name': 'メイン画面項目設定',
                'verbose_name_plural': 'メイン画面項目設定',
                'db_table': 'm_menu_item_setting',
            },
        ),
        migrations.CreateModel(
            name='DepartmentViewScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('merge', '統合'), ('split', '分割')], max_length=10, verbose_name='種別')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('viewer_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_scopes_as_viewer', to='organizations.department', verbose_name='閲覧する側の部署')),
                ('visible_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_scopes_as_visible', to='organizations.department', verbose_name='閲覧可能になる部署')),
            ],
            options={
                'verbose_name': '閲覧部署範囲',
                'verbose_name_plural': '閲覧部署範囲',
                'db_table': 'm_department_view_scope',
                'constraints': [models.UniqueConstraint(fields=('viewer_department', 'visible_department'), name='unique_department_view_scope'), models.CheckConstraint(condition=models.Q(('viewer_department', models.F('visible_department')), _negated=True), name='no_self_department_view_scope')],
            },
        ),
    ]
