# Generated by Django 5.2.9 on 2026-08-19 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentViewScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('merge', '統合'), ('split', '分割')], max_length=10, verbose_name='種別')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('viewer_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_scopes_as_viewer', to='organizations.department', verbose_name='閲覧する側の部署')),
                ('visible_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_scopes_as_visible', to='organizations.department', verbose_name='閲覧可能になる部署')),
            ],
            options={
                'verbose_name': '閲覧部署範囲',
                'verbose_name_plural': '閲覧部署範囲',
                'db_table': 'm_department_view_scope',
                'constraints': [models.UniqueConstraint(fields=('viewer_department', 'visible_department'), name='unique_department_view_scope')],
            },
        ),
    ]
