# Generated by Django 5.2.9 on 2026-08-26 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '管理者'), ('manager', '所属長'), ('staff', '一般')], max_length=10, verbose_name='システム権限')),
                ('doc_retention_edit', models.BooleanField(default=False, help_text='OFFの場合、保存した文書の保存期間を編集できない（xlsx 権限管理!B172-175、Rev1.1で追加）', verbose_name='文書管理-文書(保存満了日変更)')),
                ('doc_download', models.BooleanField(default=False, verbose_name='文書管理-文書(ダウンロード)')),
                ('contract_edit', models.BooleanField(default=False, help_text='OFFの場合、対象者は契約書の保存・編集ができない（xlsx 権限管理!B193-198、Rev1.2で新規追加）。保存不可＝メイン画面の保管枠内「契約書」ボタン非表示、編集不可＝契約書詳細画面の「編集」「削除」ボタン非表示、として制御する（permissions.services.can_edit_contract参照）。', verbose_name='契約書-契約書(契約書情報変更)')),
                ('contract_download', models.BooleanField(default=False, verbose_name='契約書-契約書(ダウンロード)')),
                ('eapproval_view_setting', models.BooleanField(default=False, verbose_name='電子決裁-書類毎の閲覧設定')),
                ('eapproval_doc_name_manage', models.BooleanField(default=False, verbose_name='電子決裁-書類名(作成・変更)')),
                ('eapproval_retention', models.BooleanField(default=False, verbose_name='電子決裁-申請書(保存期間)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('contract_visible_departments', models.ManyToManyField(blank=True, help_text='この職員が契約書検索画面の「部署」で自部署以外に選択できる部署の一覧（xlsx 権限管理!B182-183・検索・閲覧・変更!B421-423、Rev1.1で真偽値から複数選択に変更）', related_name='+', to='organizations.department', verbose_name='契約書-部門間閲覧設定')),
                ('contract_visible_groups', models.ManyToManyField(blank=True, related_name='+', to='masters.group', verbose_name='契約書-分類(表示)')),
                ('doc_visible_groups', models.ManyToManyField(blank=True, help_text='この職員が保存/検索時に選択できる分類の一覧（xlsx 権限管理!B167-170）', related_name='+', to='masters.group', verbose_name='文書管理-分類(表示)')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission_profile', to=settings.AUTH_USER_MODEL, verbose_name='職員')),
            ],
            options={
                'verbose_name': '権限管理',
                'verbose_name_plural': '権限管理',
                'db_table': 't_staff_permission',
            },
        ),
    ]
