# Generated by Django 5.2.9 on 2026-08-12 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '管理者'), ('manager', '所属長'), ('staff', '一般')], max_length=10, verbose_name='システム権限')),
                ('doc_cross_department_view', models.BooleanField(default=False, verbose_name='文書管理-部門間閲覧設定')),
                ('doc_manager_permission_grant', models.BooleanField(default=False, verbose_name='文書管理-所属長への権限付与')),
                ('doc_staff_permission_grant', models.BooleanField(default=False, help_text='詳細不明（要再確認No.5、権限管理!B193）', verbose_name='文書管理-職員への権限付与')),
                ('doc_department_edit', models.BooleanField(default=False, verbose_name='文書管理-部署・事業所(作成・変更)')),
                ('doc_group_manage', models.BooleanField(default=False, verbose_name='文書管理-分類(作成・変更・削除)')),
                ('doc_category_manage', models.BooleanField(default=False, verbose_name='文書管理-カテゴリー(作成・変更・削除)')),
                ('doc_download', models.BooleanField(default=False, verbose_name='文書管理-文書(ダウンロード)')),
                ('contract_cross_department_view', models.BooleanField(default=False, verbose_name='契約書-部門間閲覧設定')),
                ('contract_manager_permission_grant', models.BooleanField(default=False, verbose_name='契約書-所属長への権限付与')),
                ('contract_staff_permission_grant', models.BooleanField(default=False, help_text='詳細不明（要再確認No.13、権限管理!B226）', verbose_name='契約書-職員への権限付与')),
                ('contract_department_edit', models.BooleanField(default=False, verbose_name='契約書-部署・事業所(作成・変更)')),
                ('contract_group_manage', models.BooleanField(default=False, verbose_name='契約書-分類(作成・変更・削除)')),
                ('contract_category_manage', models.BooleanField(default=False, verbose_name='契約書-カテゴリー(作成・変更・削除)')),
                ('contract_download', models.BooleanField(default=False, verbose_name='契約書-契約書(ダウンロード)')),
                ('eapproval_view_setting', models.BooleanField(default=False, verbose_name='電子決裁-書類毎の閲覧設定')),
                ('eapproval_doc_name_manage', models.BooleanField(default=False, verbose_name='電子決裁-書類名(作成・変更)')),
                ('eapproval_retention', models.BooleanField(default=False, verbose_name='電子決裁-申請書(保存期間)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('contract_visible_groups', models.ManyToManyField(blank=True, related_name='+', to='masters.group', verbose_name='契約書-分類(表示)')),
                ('doc_visible_groups', models.ManyToManyField(blank=True, help_text='所属長が設定した、この職員が保存/検索時に選択できる分類の一覧（xlsx 権限管理!B203-205）', related_name='+', to='masters.group', verbose_name='文書管理-分類(表示)')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission_profile', to=settings.AUTH_USER_MODEL, verbose_name='職員')),
            ],
            options={
                'verbose_name': '権限管理',
                'verbose_name_plural': '権限管理',
                'db_table': 't_staff_permission',
            },
        ),
    ]
