# Generated by Django 5.2.9 on 2026-08-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_retentionperiod_is_deleted'),
        ('organizations', '0002_departmentviewscope'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionprofile',
            name='contract_category_manage',
        ),
        migrations.RemoveField(
            model_name='permissionprofile',
            name='contract_cross_department_view',
        ),
        migrations.RemoveField(
            model_name='permissionprofile',
            name='contract_department_edit',
        ),
        migrations.RemoveField(
            model_name='permissionprofile',
            name='contract_group_manage',
        ),
        migrations.RemoveField(
            model_name='permissionprofile',
            name='contract_manager_permission_grant',
        ),
        migrations.RemoveField(
            model_name='permissionprofile',
            name='contract_staff_permission_grant',
        ),
        migrations.RemoveField(
            model_name='permissionprofile',
            name='doc_category_manage',
        ),
        migrations.RemoveField(
            model_name='permissionprofile',
            name='doc_cross_department_view',
        ),
        migrations.RemoveField(
            model_name='permissionprofile',
            name='doc_department_edit',
        ),
        migrations.RemoveField(
            model_name='permissionprofile',
            name='doc_group_manage',
        ),
        migrations.RemoveField(
            model_name='permissionprofile',
            name='doc_manager_permission_grant',
        ),
        migrations.RemoveField(
            model_name='permissionprofile',
            name='doc_staff_permission_grant',
        ),
        migrations.AddField(
            model_name='permissionprofile',
            name='contract_visible_departments',
            field=models.ManyToManyField(blank=True, help_text='この職員が契約書検索画面の「部署」で自部署以外に選択できる部署の一覧（xlsx 権限管理!B182-183・検索・閲覧・変更!B421-423、Rev1.1で真偽値から複数選択に変更）', related_name='+', to='organizations.department', verbose_name='契約書-部門間閲覧設定'),
        ),
        migrations.AddField(
            model_name='permissionprofile',
            name='doc_retention_edit',
            field=models.BooleanField(default=False, help_text='OFFの場合、保存した文書の保存期間を編集できない（xlsx 権限管理!B172-175、Rev1.1で追加）', verbose_name='文書管理-文書(保存満了日変更)'),
        ),
        migrations.AlterField(
            model_name='permissionprofile',
            name='doc_visible_groups',
            field=models.ManyToManyField(blank=True, help_text='この職員が保存/検索時に選択できる分類の一覧（xlsx 権限管理!B167-170）', related_name='+', to='masters.group', verbose_name='文書管理-分類(表示)'),
        ),
    ]
