# Generated by Django 5.2.9 on 2026-08-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_remove_permissionprofile_contract_category_manage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionprofile',
            name='contract_edit',
            field=models.BooleanField(default=False, help_text='OFFの場合、対象者は契約書の保存・編集ができない（xlsx 権限管理!B193-198、Rev1.2で新規追加）。保存不可＝メイン画面の保管枠内「契約書」ボタン非表示、編集不可＝契約書詳細画面の「編集」「削除」ボタン非表示、として制御する（permissions.services.can_edit_contract参照）。', verbose_name='契約書-契約書(契約書情報変更)'),
        ),
    ]
