# Generated by Django 5.2.9 on 2026-08-12 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('employee_no', models.CharField(max_length=20, unique=True, verbose_name='職員番号')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('rank', models.CharField(choices=[('20', '考査役'), ('25', '調査役'), ('35', '主事'), ('70', '専任職員'), ('80', '臨時職員'), ('98', '派遣社員')], max_length=2, verbose_name='職階')),
                ('position', models.CharField(choices=[('16', '課長'), ('40', '係長'), ('60', '一般職'), ('74', '専任職員'), ('90', '臨時時給（翌月払）'), ('98', '派遣社員')], max_length=2, verbose_name='役職')),
                ('is_retired', models.BooleanField(default=False, verbose_name='退職')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Django管理サイトアクセス可否')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Django管理サイト全権限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organizations.department', verbose_name='所属部署')),
            ],
            options={
                'verbose_name': '職員',
                'verbose_name_plural': '職員マスタ',
                'db_table': 'm_staff',
            },
        ),
    ]
