# Generated by Django 5.2.9 on 2026-08-26 06:37

import django.contrib.postgres.indexes
import django.db.models.deletion
import documents.storage_paths
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('organizations', '0001_initial'),
        ('core', '0001_enable_pg_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='文書タイトル')),
                ('year', models.PositiveIntegerField(verbose_name='年')),
                ('expiry_date', models.DateField(help_text='保存日+保存期間から算出して保存する（メイン画面お知らせの「有効期限切れ」「有効期限切れまでXヶ月以内」抽出で検索条件として使うため、都度計算せず保持する）', verbose_name='保存満了日')),
                ('privacy_flag', models.BooleanField(default=True, verbose_name='個人情報が含まれる')),
                ('memo', models.TextField(blank=True, default='', verbose_name='メモ')),
                ('file', models.FileField(upload_to=documents.storage_paths.document_upload_path, verbose_name='ファイル')),
                ('extracted_text', models.TextField(blank=True, default='', help_text='ファイルから抽出した本文テキスト。フリーワード全文検索の対象', verbose_name='抽出本文')),
                ('title_normalized', models.TextField(blank=True, default='', editable=False)),
                ('memo_normalized', models.TextField(blank=True, default='', editable=False)),
                ('extracted_text_normalized', models.TextField(blank=True, default='', editable=False)),
                ('ocr_attempted', models.BooleanField(default=False, help_text='core.management.commands.extract_pending_pdf_textがOCR（Google Cloud Vision）を実行完了した場合にTrueにする。OCR結果が空文字列（画像に文字が無い等）の場合でもextracted_text=""のままだと毎回スキャン文書と判定され無限にOCRが再実行されてしまうため、このフラグで一度実行済みのレコードをバッチの対象から除外する（一時的なAPIエラーで例外が起きた場合はセットしないため次回リトライされる）。', verbose_name='OCR実行済み')),
                ('searchable_file', models.FileField(blank=True, help_text='settings.OCR_EMBED_TEXT_TO_PDF=Trueかつprivacy_flag=False（個人情報を含まない）の場合のみ、スキャン文書のOCR結果を透明テキストとして埋め込んだPDFをcore.management.commands.extract_pending_pdf_textが生成する（既定はnull＝未生成）。個人情報を含む文書（privacy_flag=True）は検索用PDFへの複製を避けるため対象外とする（2026-08-19追加）。原本（fileフィールド）は変更せず別ファイルとして保持する（監査・原本性の観点）。', null=True, upload_to=documents.storage_paths.document_searchable_upload_path, verbose_name='検索用PDF（OCRテキスト埋め込み版）')),
                ('save_date', models.DateTimeField(auto_now_add=True, verbose_name='保存日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除済み')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='masters.category', verbose_name='カテゴリー')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='organizations.department', verbose_name='保管先部署')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='masters.group', verbose_name='分類')),
                ('retention_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='masters.retentionperiod', verbose_name='保存期間')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='保管・更新者')),
            ],
            options={
                'verbose_name': '文書',
                'verbose_name_plural': '文書',
                'db_table': 't_document',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['extracted_text'], name='doc_extracted_text_trgm', opclasses=['gin_trgm_ops']), django.contrib.postgres.indexes.GinIndex(fields=['extracted_text_normalized'], name='doc_extracted_text_norm_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
