# Generated by Django 5.2.9 on 2026-08-26 06:37

import django.contrib.postgres.indexes
import core.upload_validation
import django.core.validators
import django.db.models.deletion
import documents.storage_paths
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('organizations', '0001_initial'),
        ('core', '0001_enable_pg_trgm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='文書タイトル')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2200)], verbose_name='年')),
                ('expiry_date', models.DateField(db_index=True, help_text='保存日+保存期間から算出して保存する（メイン画面お知らせの「有効期限切れ」「有効期限切れまでXヶ月以内」抽出で検索条件として使うため、都度計算せず保持する）', verbose_name='保存満了日')),
                ('privacy_flag', models.BooleanField(default=True, verbose_name='個人情報が含まれる')),
                ('memo', models.TextField(blank=True, default='', verbose_name='メモ')),
                ('file', models.FileField(upload_to=documents.storage_paths.document_upload_path, validators=[core.upload_validation.validate_no_active_content], verbose_name='ファイル')),
                ('title_normalized', models.TextField(blank=True, default='', editable=False)),
                ('memo_normalized', models.TextField(blank=True, default='', editable=False)),
                ('extracted_text_normalized', models.TextField(blank=True, default='', editable=False)),
                ('text_extracted', models.BooleanField(db_index=True, default=False, help_text='テキスト層抽出または OCR による本文抽出が完了したら True（結果が空文字列でも完了は完了）。core.management.commands.extract_pending_pdf_text は False のレコードだけを対象にする。誤OCR等で再抽出させたい場合は運用手順で False に戻す（監査 案2、2026-09-11。旧 ocr_attempted＋extracted_text="" 判定を1フラグに統合）。', verbose_name='本文抽出済み')),
                ('ocr_textdata', models.JSONField(blank=True, editable=False, help_text='スキャン文書の OCR 行レイアウト（core.ocr_layout_services.textdatas_to_json 形式）。検索用PDF（OCRテキスト埋め込み版）を core.searchable_pdf_services が必要時に生成するための元データ。settings.OCR_STORE_TEXTDATA=True かつ privacy_flag=False（個人情報を含まない）のスキャン文書でのみ保存する（個人情報の本文を DB へ複製しないため）。テキスト層PDF・privacy_flag=True の文書は null（監査 案3、2026-09-11。旧 searchable_file〈埋め込み済みPDFの恒久保存〉を、桁違いに小さい座標データの保存＋遅延生成に置き換えた）。', null=True, verbose_name='OCR座標データ')),
                ('save_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='保存日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除済み')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='削除日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='masters.category', verbose_name='カテゴリー')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='organizations.department', verbose_name='保管先部署')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='masters.group', verbose_name='分類')),
                ('retention_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='masters.retentionperiod', verbose_name='保存期間')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='保管・更新者')),
            ],
            options={
                'verbose_name': '文書',
                'verbose_name_plural': '文書',
                'db_table': 't_document',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['title_normalized'], name='doc_title_norm_trgm', opclasses=['gin_trgm_ops']), django.contrib.postgres.indexes.GinIndex(fields=['memo_normalized'], name='doc_memo_norm_trgm', opclasses=['gin_trgm_ops']), django.contrib.postgres.indexes.GinIndex(fields=['extracted_text_normalized'], name='doc_extracted_text_norm_trgm', opclasses=['gin_trgm_ops']), models.Index(condition=models.Q(('is_deleted', True)), fields=['deleted_at'], name='doc_deleted_at_partial')],
            },
        ),
    ]
