# Generated by Django 5.2.9 on 2026-08-24 00:12

import documents.storage_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_backfill_normalized_search_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='searchable_file',
            field=models.FileField(blank=True, help_text='settings.OCR_EMBED_TEXT_TO_PDF=Trueかつprivacy_flag=False（個人情報を含まない）の場合のみ、スキャン文書のOCR結果を透明テキストとして埋め込んだPDFをcore.management.commands.extract_pending_pdf_textが生成する（既定はnull＝未生成）。個人情報を含む文書（privacy_flag=True）は検索用PDFへの複製を避けるため対象外とする（2026-08-19追加）。原本（fileフィールド）は変更せず別ファイルとして保持する（監査・原本性の観点）。', null=True, upload_to=documents.storage_paths.document_searchable_upload_path, verbose_name='検索用PDF（OCRテキスト埋め込み版）'),
        ),
    ]
