# Generated by Django 5.2.9 on 2026-08-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_searchable_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title_normalized',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
