# Generated by Django 5.2.9 on 2026-08-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作日時')),
                ('employee_no', models.CharField(max_length=20, verbose_name='職員番号')),
                ('employee_name', models.CharField(max_length=100, verbose_name='職員名')),
                ('department_name', models.CharField(max_length=200, verbose_name='部署名')),
                ('action', models.CharField(help_text='「画面名 ＋ 全角スペース ＋ ボタン名」形式（xlsx 操作履歴ログ!B63）', max_length=100, verbose_name='操作内容')),
                ('event_message', models.TextField(verbose_name='イベントメッセージ')),
                ('personal_info_flag', models.BooleanField(default=False, help_text='個人情報書類フラグがセットされた文書を扱ったイベントか（xlsx 操作履歴ログ!B43）', verbose_name='個人情報')),
            ],
            options={
                'verbose_name': '操作履歴ログ',
                'verbose_name_plural': '操作履歴ログ',
                'db_table': 't_audit_log',
                'indexes': [models.Index(fields=['-timestamp'], name='t_audit_log_timesta_894930_idx')],
            },
        ),
    ]
