# Generated by Django 5.2.9 on 2026-08-25 22:07

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        # gin_trgm_ops opclassはpg_trgm拡張が必要（documents/contracts側は依存を明示していないが、
        # 実際にはこの明示が無いとテストDB構築時のマイグレーション適用順序次第でpg_trgm拡張の
        # 有効化前にCREATE INDEX ... USING GIN (...) gin_trgm_opsが実行され失敗する
        # 〈ProgrammingError: operator class "gin_trgm_ops" does not exist〉。品質レビューでの
        # 修正時に実際に検出したため、ここでは明示的に依存させる。
        ('core', '0001_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Replace(django.db.models.functions.text.Replace(models.F('employee_name'), models.Value('\u3000'), models.Value('')), models.Value(' '), models.Value('')), name='gin_trgm_ops'), name='auditlog_employee_name_trgm'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['event_message'], name='auditlog_event_message_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
